version: '2'

services:
  influxdb:
    image: influxdb
    container_name: 'influxdb'
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - 8083:8083
      - 8086:8086

  grafana:
    image: grafana/grafana
    container_name: 'grafana'
    ports:
      - 8085:3000
    volumes:
      - ./data/grafana:/var/lib/grafana
