version: "3"

services:
  nginx:
    image: nginx
    container_name: some-nginx
    restart: always
    volumes:
      - ./mysite.template:/etc/nginx/conf.d/mysite.template:ro
      - ./html:/usr/share/nginx/html
    ports:
      - "8080:80"
    environment:
      - NGINX_HOST=192.168.33.10
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

volumes:
  data:
