# Usage
# up: `docker-compose up -d`
# down: `docker-compose down -v`

version: "3"

services:
  mongo:
    build: mongo
    container_name: some-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

volumes:
  data:
